// <auto-generated />
using System;
using GestorDeTareas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorDeTareas.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GestorDeTareasDbContext))]
    [Migration("20260604005845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorDeTareas.Domain.Entities.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pilar")
                        .HasColumnType("int");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Tareas");

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GestorDeTareas.Domain.Entities.TareaProfunda", b =>
                {
                    b.HasBaseType("GestorDeTareas.Domain.Entities.Tarea");

                    b.Property<string>("Intencion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("GestorDeTareas.Domain.Entities.TareaSimple", b =>
                {
                    b.HasBaseType("GestorDeTareas.Domain.Entities.Tarea");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("GestorDeTareas.Domain.Entities.TareaUrgente", b =>
                {
                    b.HasBaseType("GestorDeTareas.Domain.Entities.Tarea");

                    b.HasDiscriminator().HasValue(2);
                });
#pragma warning restore 612, 618
        }
    }
}
