@baseUrl = http://localhost:5269
@token = MALA_PRACTICA_NO_SUBO_TOKEN_A_GITHUB
@tareaId = MALA_PRACTICA_NO_SUBO_ID_A_GITHUB


### Registrar usuario
POST {{baseUrl}}/api/auth/registro
Content-Type: application/json

{
  "nombre": "Pedro",
  "email": "pedro@test.com",
  "password": "123456"
}


### Login usuario
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "pedro@test.com",
  "password": "123456"
}


### Intentar obtener tareas sin token 
GET {{baseUrl}}/api/tareas


### Obtener todas las tareas con token
GET {{baseUrl}}/api/tareas
Authorization: Bearer {{token}}


### Crear tarea simple con token
POST {{baseUrl}}/api/tareas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titulo": "Estudiar Angular",
  "fechaLimite": "2026-12-31",
  "prioridad": 2,
  "pilar": 2,
  "tipo": 1,
  "intencion": null
}


### Crear tarea urgente con token
POST {{baseUrl}}/api/tareas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titulo": "Entregar proyecto",
  "fechaLimite": "2026-12-31",
  "prioridad": 4,
  "pilar": 2,
  "tipo": 2,
  "intencion": null
}


### Crear tarea profunda con token
POST {{baseUrl}}/api/tareas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titulo": "Reflexionar sobre el avance del proyecto",
  "fechaLimite": "2026-12-31",
  "prioridad": 2,
  "pilar": 5,
  "tipo": 3,
  "intencion": "Avanzar con calma y constancia"
}


### Obtener todas las tareas después de crear
GET {{baseUrl}}/api/tareas
Authorization: Bearer {{token}}


### Obtener tarea por id
GET {{baseUrl}}/api/tareas/{{tareaId}}
Authorization: Bearer {{token}}


### Actualizar tarea
PUT {{baseUrl}}/api/tareas/{{tareaId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titulo": "Estudiar Angular actualizado",
  "fechaLimite": "2026-12-31",
  "prioridad": 3,
  "estado": 2,
  "pilar": 2,
  "intencion": null
}


### Comprobar tarea actualizada
GET {{baseUrl}}/api/tareas/{{tareaId}}
Authorization: Bearer {{token}}


### Completar tarea
PATCH {{baseUrl}}/api/tareas/{{tareaId}}/completar
Authorization: Bearer {{token}}


### Comprobar tarea completada
GET {{baseUrl}}/api/tareas/{{tareaId}}
Authorization: Bearer {{token}}


### Eliminar tarea
DELETE {{baseUrl}}/api/tareas/{{tareaId}}
Authorization: Bearer {{token}}


### Comprobar que se ha eliminado 
GET {{baseUrl}}/api/tareas/{{tareaId}}
Authorization: Bearer {{token}}


### Obtener todas las tareas después de eliminar
GET {{baseUrl}}/api/tareas
Authorization: Bearer {{token}}